In [1]:
import numpy as np

In [2]:
# 创建一个一维数组，将其倒置，输出结果
ANarr = np.arange(8)
ANarr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
di_ANarr = ANarr[::-1]
di_ANarr

array([7, 6, 5, 4, 3, 2, 1, 0])

In [12]:
# 创建一个5x5的每行都为0到4的二维数组
arrOrg = np.zeros((5,5))
arr = np.arange(5)
arrOrg[:] = arr
arrOrg

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [9]:
np.vstack((arr, arr, arr, arr, arr))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [23]:
# 创建一个10x10的数组，外边都是1，里面都是0
zero10 = np.zeros((10,10))
zero10[0,] = 1
zero10[-1,]= 1
zero10[:,0] = 1
zero10[:,-1]= 1
zero10

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])